/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndn_jwtan_identitymanager_NdncertClient */

#ifndef _Included_com_ndn_jwtan_identitymanager_NdncertClient
#define _Included_com_ndn_jwtan_identitymanager_NdncertClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndn_jwtan_identitymanager_NdncertClient
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndn_jwtan_identitymanager_NdncertClient_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
